# Generated by Django 6.1.1 on 2026-09-28 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('star_rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1, message='Star rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Star rating cannot exceed 5.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city'], name='hotels_city_11256f_idx'), models.Index(fields=['star_rating'], name='hotels_star_ra_c9e890_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite')], default='SINGLE', max_length=10)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Price cannot be negative.')])),
                ('capacity', models.PositiveSmallIntegerField(help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1.'), django.core.validators.MaxValueValidator(10, message='Capacity cannot exceed 10.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['hotel', 'room_number'],
                'indexes': [models.Index(fields=['hotel'], name='rooms_hotel_i_fc2043_idx'), models.Index(fields=['room_type'], name='rooms_room_ty_7b8350_idx'), models.Index(fields=['price_per_night'], name='rooms_price_p_db2697_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'room_number'), name='unique_room_per_hotel')],
            },
        ),
    ]
