"""
Django settings for bookingmangment project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fk1!w6mbgtv_jt@sjm=!x&#-2ike4b30z8ywh_jugsj4jg@r$x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking',
    'hotels',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt', 
    'drf_spectacular',
       
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookingmangment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


import os
from datetime import timedelta

X_SERVICE_TOKEN = os.environ.get("X_SERVICE_TOKEN", "fallback-dev-token")
X_SERVICE_TOKEN_HEADER = "HTTP_X_SERVICE_TOKEN"

AUTH_SERVICE_URL = os.environ.get("AUTH_SERVICE_URL", "http://127.0.0.1:8000")


SPECTACULAR_SETTINGS = {
    'TITLE': 'Booking Service API',
    'DESCRIPTION': (
        "Hotel & Room Booking\n\n"
        "**Endpoints:**\n"
        "- GET /api/hotels/ — list hotels\n"
        "- GET /api/hotels/{id}/ — hotel detail\n"
        "- GET/POST /api/rooms/ — list & create rooms\n"
        "- GET/PUT/DELETE /api/rooms/{id}/ — room detail\n"
        "- GET/POST /api/bookings/ — list & create bookings\n"
        "- GET/PUT/DELETE /api/bookings/{id}/ — booking detail\n"
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

}
REST_FRAMEWORK = {
    # Swagger schema inspector (fixes the AssertionError)
     'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # JWT authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'booking.authentication.StatelessJWTAuthentication',
    ),

    # Filtering
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
   
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',    # default for hotels/rooms
    ),
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'SIGNING_KEY': 'dev-shared-key-123456',   # ← THE FIX: same value in both services
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}



# CELERY

# ─────────────────────────────────────────────
# CELERY
# ─────────────────────────────────────────────
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# ─────────────────────────────────────────────
# CELERY BEAT — PERIODIC TASKS
# ─────────────────────────────────────────────
CELERY_BEAT_SCHEDULE = {
    # هر ۵ دقیقه: Booking های گذشته را COMPLETED کن
    'complete-past-bookings': {
        'task': 'booking.tasks.complete_past_bookings',
        'schedule': 300.0,   # 5 دقیقه (به ثانیه)
    },

    # هر ۱۰ دقیقه: Booking های PENDING قدیمی را CANCELLED کن
    'cancel-stale-pending-bookings': {
        'task': 'booking.tasks.cancel_stale_pending_bookings',
        'schedule': 600.0,   # 10 دقیقه
    },
}
ROOT_URLCONF = 'bookingmangment.urls'
